version: '3'
services:
  flask_simple:
    build: 
      context: ./
      dockerfile: docker/flask_simple/Dockerfile
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    env_file:
      - docker/flask_simple.env
    command: flask run --host=0.0.0.0
    ports:
      - 5000:5000
    restart: "no"
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: ""
    ports:
      - 5432:5432
    restart: "no"